name: Deploy service

on:
  push:
    branches: ["main"]
    paths:
      - "service/**"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "kosher"
          heroku_email: "danielgospodinow@gmail.com"
        appdir: "service"
